"""Creek generate package — index and note generation for the Creek vault."""

from creek.generate.compost import (
    CompostCandidate,
    CompostTracker,
)
from creek.generate.compost_calibration import (
    DEFAULT_FIXTURE_PATH as COMPOST_CALIBRATION_FIXTURE_PATH,
)
from creek.generate.compost_calibration import (
    CompostCalibrationEntry,
    CompostCalibrationReport,
    CompostEntryScore,
    CompostFloorBreachError,
    score_compost,
)
from creek.generate.compost_calibration import (
    assert_floors as assert_compost_floors,
)
from creek.generate.compost_calibration import (
    load_fixture as load_compost_fixture,
)
from creek.generate.compost_calibration import (
    write_json_sidecar as write_compost_json_sidecar,
)
from creek.generate.compost_embedding import (
    PACKAGED_EXEMPLARS_PATH,
    CompostExemplar,
    load_exemplars,
    make_similarity_fn,
)
from creek.generate.compost_verifier import (
    CompostVerdict,
    CompostVerifierResult,
    LLMCompostVerifier,
    SupportsVerifyCompost,
)
from creek.generate.decisions import (
    DECISION_KEYWORDS,
    PRACTICE_MAP,
    DecisionContext,
    DecisionContextGatherer,
    DecisionDetector,
    decision_from_note,
)
from creek.generate.drafts import (
    DRAFTS_SUBDIR,
    Draft,
    DraftGenerator,
    DraftLLM,
)
from creek.generate.indexes import FREQUENCY_COLORS, FREQUENCY_NAMES, IndexGenerator
from creek.generate.lexicon import (
    TRADITION_GLOSSARIES,
    BorrowedTermEntry,
    CoinedTermEntry,
    DistinctivePhraseEntry,
    Lexicon,
    LexiconContext,
    LexiconGenerator,
    MetaphorInventory,
)
from creek.generate.mining import (
    DEFAULT_MIN_CHAIN_LENGTH,
    DEFAULT_SIMILARITY_LIMINAL,
    DEFAULT_SIMILARITY_RESONANCE,
    IdeaMiner,
    IdeaSeed,
    MiningSnapshot,
    MiningStrategy,
)
from creek.generate.paradox import (
    CONTRADICTION_KEYWORDS,
    REFLECTION_PROMPT,
    Paradox,
    ParadoxDetector,
)
from creek.generate.skills import (
    DEFAULT_MAX_EXEMPLARS,
    DEFAULT_MIN_EDDY_FRAGMENTS,
    DEFAULT_MIN_EXEMPLARS,
    DEFAULT_MIN_THREAD_FRAGMENTS,
    FREQUENCY_KEYS,
    FREQUENCY_MEDICINE_VS_TOXIC,
    FREQUENCY_VOICE_TEXTURES,
    MODE_ORIENTATION_KEYS,
    MODE_ORIENTATION_STANCES,
    PHASE_KEYS,
    PHASE_VOICE_RHYTHMS,
    REGISTER_ANTI_PATTERNS,
    REGISTER_KEYS,
    REGISTER_VOICE_PROMPTS,
    SkillExemplar,
    SkillTreeGenerator,
    VaultSnapshot,
)
from creek.generate.state import (
    EMPTY_PLACEHOLDER,
    SECTION_ORDER,
    StateReportGenerator,
)
from creek.generate.synchronicity import (
    DEFAULT_MIN_TIME_GAP_DAYS,
    DEFAULT_SIMILARITY_THRESHOLD,
    SynchronicityDetector,
)
from creek.generate.tags import TagGardenGenerator, TagScanResult
from creek.generate.voice import (
    DEFAULT_MAX_PER_REGISTER,
    DEFAULT_MIN_PER_REGISTER,
    METAPHOR_DOMAINS,
    VOICE_REGISTERS,
    MetaphorFamily,
    ParagraphMetrics,
    PunctuationHabits,
    RhetoricalMoves,
    SentenceMetrics,
    VocabularyFingerprint,
    VoiceExemplarCollector,
    VoicePatternExtractor,
    VoicePatterns,
)
from creek.generate.wavelength import (
    DEFAULT_ROLLING_WEEKS,
    DEFAULT_TOXIC_CONSECUTIVE_WEEKS,
    DEFAULT_TOXIC_THRESHOLD,
    DEFAULT_WINDOW_DAYS,
    DosageTrend,
    PhaseTransition,
    WavelengthSnapshot,
    WavelengthTracker,
)

__all__ = [
    "COMPOST_CALIBRATION_FIXTURE_PATH",
    "CONTRADICTION_KEYWORDS",
    "DECISION_KEYWORDS",
    "DEFAULT_MAX_EXEMPLARS",
    "DEFAULT_MAX_PER_REGISTER",
    "DEFAULT_MIN_CHAIN_LENGTH",
    "DEFAULT_MIN_EDDY_FRAGMENTS",
    "DEFAULT_MIN_EXEMPLARS",
    "DEFAULT_MIN_PER_REGISTER",
    "DEFAULT_MIN_THREAD_FRAGMENTS",
    "DEFAULT_MIN_TIME_GAP_DAYS",
    "DEFAULT_ROLLING_WEEKS",
    "DEFAULT_SIMILARITY_LIMINAL",
    "DEFAULT_SIMILARITY_RESONANCE",
    "DEFAULT_SIMILARITY_THRESHOLD",
    "DEFAULT_TOXIC_CONSECUTIVE_WEEKS",
    "DEFAULT_TOXIC_THRESHOLD",
    "DEFAULT_WINDOW_DAYS",
    "DRAFTS_SUBDIR",
    "EMPTY_PLACEHOLDER",
    "FREQUENCY_COLORS",
    "FREQUENCY_KEYS",
    "FREQUENCY_MEDICINE_VS_TOXIC",
    "FREQUENCY_NAMES",
    "FREQUENCY_VOICE_TEXTURES",
    "METAPHOR_DOMAINS",
    "MODE_ORIENTATION_KEYS",
    "MODE_ORIENTATION_STANCES",
    "PACKAGED_EXEMPLARS_PATH",
    "PHASE_KEYS",
    "PHASE_VOICE_RHYTHMS",
    "PRACTICE_MAP",
    "REFLECTION_PROMPT",
    "REGISTER_ANTI_PATTERNS",
    "REGISTER_KEYS",
    "REGISTER_VOICE_PROMPTS",
    "SECTION_ORDER",
    "TRADITION_GLOSSARIES",
    "VOICE_REGISTERS",
    "BorrowedTermEntry",
    "CoinedTermEntry",
    "CompostCalibrationEntry",
    "CompostCalibrationReport",
    "CompostCandidate",
    "CompostEntryScore",
    "CompostExemplar",
    "CompostFloorBreachError",
    "CompostTracker",
    "CompostVerdict",
    "CompostVerifierResult",
    "DecisionContext",
    "DecisionContextGatherer",
    "DecisionDetector",
    "DistinctivePhraseEntry",
    "DosageTrend",
    "Draft",
    "DraftGenerator",
    "DraftLLM",
    "IdeaMiner",
    "IdeaSeed",
    "IndexGenerator",
    "LLMCompostVerifier",
    "Lexicon",
    "LexiconContext",
    "LexiconGenerator",
    "MetaphorFamily",
    "MetaphorInventory",
    "MiningSnapshot",
    "MiningStrategy",
    "Paradox",
    "ParadoxDetector",
    "ParagraphMetrics",
    "PhaseTransition",
    "PunctuationHabits",
    "RhetoricalMoves",
    "SentenceMetrics",
    "SkillExemplar",
    "SkillTreeGenerator",
    "StateReportGenerator",
    "SupportsVerifyCompost",
    "SynchronicityDetector",
    "TagGardenGenerator",
    "TagScanResult",
    "VaultSnapshot",
    "VocabularyFingerprint",
    "VoiceExemplarCollector",
    "VoicePatternExtractor",
    "VoicePatterns",
    "WavelengthSnapshot",
    "WavelengthTracker",
    "assert_compost_floors",
    "decision_from_note",
    "load_compost_fixture",
    "load_exemplars",
    "make_similarity_fn",
    "score_compost",
    "write_compost_json_sidecar",
]
