"""Authorship tagger — classify fragment authors as self, ai, other, or collaborative.

Evaluates fragment metadata and source platform to determine authorship.
Each fragment receives one of four author types:

- **self**: Content authored by the vault owner
- **ai**: Content generated by an AI assistant (Claude, ChatGPT)
- **other**: Content authored by someone else
- **collaborative**: Content with contributions from both self and others

Source-specific inference rules:

- **Claude/ChatGPT**: Human/user turns → self; assistant/system turns → ai.
- **Discord**: Matches author names against configured self-usernames.
  Self-only → self; others-only → other; mixed → collaborative.
- **Journal/Essay**: Defaults to self unless metadata indicates otherwise.
- **Code**: Matches commit authors against configured self-usernames.
- **Email**: Matches sender against configured self-usernames.
- **Other/Unknown**: Flagged for human review.

Ambiguous cases (collaborative content, missing metadata, unknown platforms)
are flagged with ``needs_review=True`` for human review.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_CHAT_PLATFORMS: frozenset[str] = frozenset({"claude", "chatgpt"})
"""Platforms that follow the human/assistant turn convention."""

_SELF_PLATFORMS: frozenset[str] = frozenset({"journal", "essay"})
"""Platforms where content defaults to self-authored."""

_AUTHOR_PLATFORMS: frozenset[str] = frozenset({"discord", "code", "email"})
"""Platforms that use author-list-based identification."""

_HUMAN_ROLES: frozenset[str] = frozenset({"human", "user"})
"""Metadata role values that indicate a human (self) turn."""

_AI_ROLES: frozenset[str] = frozenset({"assistant", "system"})
"""Metadata role values that indicate an AI turn."""


# ---------------------------------------------------------------------------
# Result model
# ---------------------------------------------------------------------------


class AuthorshipResult(BaseModel):
    """Structured result from authorship tagging.

    Attributes:
        author: The inferred author type.
        confidence: Confidence in the inference, in [0.0, 1.0].
        needs_review: Whether the result should be reviewed by a human.
        reasons: Human-readable explanations of the tagging decision.
    """

    author: Literal["self", "ai", "other", "collaborative"]
    confidence: float = Field(ge=0.0, le=1.0)
    needs_review: bool
    reasons: list[str]


# ---------------------------------------------------------------------------
# Tagger
# ---------------------------------------------------------------------------


class AuthorshipTagger:
    """Classify fragment authorship using platform and metadata heuristics.

    Applies source-specific inference rules to determine whether a fragment
    was authored by the vault owner (self), an AI assistant, another person,
    or collaboratively. Ambiguous cases are flagged for human review.

    Attributes:
        self_usernames: Lowercase frozenset of usernames belonging to the
            vault owner, used for Discord/code/email identification.
    """

    def __init__(
        self,
        *,
        self_usernames: set[str] | frozenset[str] | None = None,
    ) -> None:
        """Initialise the tagger with configurable self-identification.

        Args:
            self_usernames: Set of usernames that identify the vault owner
                across platforms (e.g., Discord usernames, Git commit
                authors). Stored lowercase for case-insensitive matching.
        """
        if self_usernames is None:
            self.self_usernames: frozenset[str] = frozenset()
        else:
            self.self_usernames = frozenset(u.lower() for u in self_usernames)

    def tag(
        self,
        platform: str,
        metadata: dict[str, Any],
    ) -> AuthorshipResult:
        """Tag a fragment with its authorship classification.

        Routes to platform-specific inference logic based on the source
        platform string. Returns a structured result with the author type,
        confidence level, and any review flags.

        Args:
            platform: The source platform (e.g., ``claude``, ``discord``).
            metadata: Fragment metadata dict containing platform-specific
                fields like ``role``, ``authors``, or ``author``.

        Returns:
            An :class:`AuthorshipResult` with the inferred authorship.
        """
        if platform in _CHAT_PLATFORMS:
            return self._tag_chat(platform, metadata)
        if platform in _SELF_PLATFORMS:
            return self._tag_self_platform(platform, metadata)
        if platform in _AUTHOR_PLATFORMS:
            return self._tag_author_platform(platform, metadata)
        return self._tag_unknown(platform)

    # ---- Platform-specific taggers ----

    def _tag_chat(
        self,
        platform: str,
        metadata: dict[str, Any],
    ) -> AuthorshipResult:
        """Tag a chat-platform fragment using role metadata.

        Args:
            platform: The chat platform name.
            metadata: Fragment metadata; expects a ``role`` key.

        Returns:
            An :class:`AuthorshipResult` based on the conversation role.
        """
        role = metadata.get("role", "").lower()

        if role in _HUMAN_ROLES:
            return AuthorshipResult(
                author="self",
                confidence=0.95,
                needs_review=False,
                reasons=[f"Human turn in {platform} conversation"],
            )

        if role in _AI_ROLES:
            return AuthorshipResult(
                author="ai",
                confidence=0.95,
                needs_review=False,
                reasons=[f"AI turn (role={role}) in {platform} conversation"],
            )

        return AuthorshipResult(
            author="self",
            confidence=0.3,
            needs_review=True,
            reasons=[
                f"No role metadata for {platform} fragment; cannot determine author"
            ],
        )

    def _tag_self_platform(
        self,
        platform: str,
        metadata: dict[str, Any],
    ) -> AuthorshipResult:
        """Tag a self-authored platform fragment (journal, essay).

        Defaults to self unless an explicit ``author`` metadata key
        indicates otherwise.

        Args:
            platform: The platform name.
            metadata: Fragment metadata; may contain ``author`` key.

        Returns:
            An :class:`AuthorshipResult` defaulting to self.
        """
        explicit_author = metadata.get("author")

        if explicit_author is not None and str(explicit_author).strip():
            return AuthorshipResult(
                author="other",
                confidence=0.7,
                needs_review=False,
                reasons=[f"Explicit author '{explicit_author}' in {platform} metadata"],
            )

        return AuthorshipResult(
            author="self",
            confidence=0.85,
            needs_review=False,
            reasons=[f"Default self-authored {platform} content"],
        )

    def _tag_author_platform(
        self,
        platform: str,
        metadata: dict[str, Any],
    ) -> AuthorshipResult:
        """Tag a fragment using author-list metadata.

        Compares authors from metadata against configured self-usernames
        to determine self, other, or collaborative authorship.

        Args:
            platform: The platform name.
            metadata: Fragment metadata; expects an ``authors`` key.

        Returns:
            An :class:`AuthorshipResult` based on author identification.
        """
        raw_authors: list[Any] = metadata.get("authors", [])
        authors = _clean_authors(raw_authors)

        if not authors:
            return AuthorshipResult(
                author="self",
                confidence=0.2,
                needs_review=True,
                reasons=[f"No authors found in {platform} metadata"],
            )

        if not self.self_usernames:
            return AuthorshipResult(
                author="self",
                confidence=0.2,
                needs_review=True,
                reasons=[
                    f"No self-usernames configured; "
                    f"cannot identify authorship in {platform}"
                ],
            )

        return self._classify_authors(platform, authors)

    def _classify_authors(
        self,
        platform: str,
        authors: list[str],
    ) -> AuthorshipResult:
        """Classify authorship from a cleaned list of author names.

        Args:
            platform: The platform name for reason messages.
            authors: Non-empty list of cleaned, lowercased author names.

        Returns:
            An :class:`AuthorshipResult` with self/other/collaborative.
        """
        self_authors = [a for a in authors if a in self.self_usernames]
        other_authors = [a for a in authors if a not in self.self_usernames]

        if self_authors and other_authors:
            return AuthorshipResult(
                author="collaborative",
                confidence=0.75,
                needs_review=True,
                reasons=[
                    f"Mixed authorship in {platform}: "
                    f"self={self_authors}, others={other_authors}"
                ],
            )

        if self_authors:
            return AuthorshipResult(
                author="self",
                confidence=0.9,
                needs_review=False,
                reasons=[f"Self-authored {platform} content by {self_authors}"],
            )

        return AuthorshipResult(
            author="other",
            confidence=0.9,
            needs_review=False,
            reasons=[f"Other-authored {platform} content by {other_authors}"],
        )

    def _tag_unknown(self, platform: str) -> AuthorshipResult:
        """Tag a fragment from an unknown or ambiguous platform.

        Args:
            platform: The platform name.

        Returns:
            An :class:`AuthorshipResult` flagged for human review.
        """
        return AuthorshipResult(
            author="self",
            confidence=0.2,
            needs_review=True,
            reasons=[
                f"Unknown or ambiguous platform '{platform}'; flagged for human review"
            ],
        )


# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------


def _clean_authors(raw_authors: list[Any]) -> list[str]:
    """Clean and normalize a list of author names.

    Filters out ``None`` and empty-string values, converts to lowercase,
    and strips whitespace.

    Args:
        raw_authors: Raw author list from fragment metadata.

    Returns:
        A deduplicated list of cleaned, lowercased author names.
    """
    cleaned: list[str] = []
    seen: set[str] = set()
    for author in raw_authors:
        if author is None:
            continue
        name = str(author).strip().lower()
        if name and name not in seen:
            cleaned.append(name)
            seen.add(name)
    return cleaned
