"""The Google OAuth **web** flow, for authorising Drive over the network (#1568).

``creek gdrive --download`` mints a credential with
``InstalledAppFlow.run_local_server(port=0)``, which opens a browser on the
machine running it. That is unreachable for a remote consumer, and it is the
last unmet clause of the seeding promise (#1523): *connect Drive over the
network, with no CLI and no shell access.*

This module is the other half — the web-application flow, split into its two
legs so the leg that needs a browser can happen at the **caller**:

1. :func:`authorization_url` builds the URL the caller sends its user to. Pure
   local computation; no network, no secret disclosed.
2. :func:`exchange_code` trades the returned authorization code for a
   credential. This leg carries the client secret, so it runs here and only
   here — which is the whole reason ADR-0012 chose option C over handing the
   consumer its own Google client.

**PKCE spans both legs, so the verifier cannot be a flow-local secret.** The
library puts a ``code_challenge`` in every authorization URL it builds and
sends the matching ``code_verifier`` at exchange time. Two legs mean two flow
objects in two requests, so the verifier is minted by :func:`new_code_verifier`
and passed into :func:`build_flow` explicitly — see that function for what
happens when it is left to the library instead.

**Nothing in this module returns a secret to its caller.**
:func:`exchange_code` returns the serialised credential because that is what
gets written to the token file by the same
:func:`creek.ingest.gdrive._write_token_file` the CLI path uses; every layer
above it projects that onto connection *state*.

The Google libraries are an optional extra, exactly as they are for the
downloader, so the import sits inside :func:`build_flow` and its absence is the
same :class:`~creek.ingest.gdrive.GoogleApiUnavailableError` the downloader
raises.
"""

from __future__ import annotations

import secrets
from typing import TYPE_CHECKING, Any, Final

from creek.ingest.gdrive import GoogleApiUnavailableError

if TYPE_CHECKING:  # pragma: no cover - typing only
    from collections.abc import Sequence

CODE_VERIFIER_BYTES: Final[int] = 32
"""Entropy of the PKCE code verifier, in bytes, before url-safe encoding.

``secrets.token_urlsafe(32)`` yields 43 characters drawn from
``[A-Za-z0-9_-]`` — the shortest length RFC 7636 §4.1 permits, and a strict
subset of the ``unreserved`` alphabet it requires.
"""

_ACCESS_TYPE: Final[str] = "offline"
"""Ask for a refresh token, not merely an access token.

Without it the grant expires in an hour and no unattended sync can ever run
again — the connector would report ``expired`` within the day and the user
would have to reconnect, which is the failure this whole issue exists to end.
"""

_PROMPT: Final[str] = "consent"
"""Force the consent screen so a refresh token is always issued.

Google omits the refresh token on a re-authorisation the user has already
granted, which would leave the token file with an access token and no way to
renew it. ``prompt=consent`` costs the user one extra click and makes the
credential this flow writes always renewable.
"""

_INCLUDE_GRANTED_SCOPES: Final[str] = "false"
"""Never widen the grant by inheriting scopes from an earlier authorisation.

``include_granted_scopes=true`` is Google's incremental-authorisation switch:
it merges every scope the user previously granted this client into the new
token. Creek asks for ``drive.readonly`` and must receive exactly that, so a
credential minted here cannot inherit a write scope some other flow obtained.
"""


def new_code_verifier() -> str:
    """Return a fresh PKCE code verifier.

    Minted here, by us, rather than left to ``google_auth_oauthlib``'s
    ``autogenerate_code_verifier``. The library generates one lazily inside
    :meth:`Flow.authorization_url` and keeps it on that flow object; the two
    legs of a remote grant are two requests and therefore two flows, so an
    autogenerated verifier would be published as a ``code_challenge`` by the
    first leg and then thrown away, and the second leg would present nothing
    for Google to check. Every real exchange would fail ``invalid_grant``.
    Minting it up front is what lets the value be persisted with the ``state``
    and handed to the second flow.

    Returns:
        A verifier meeting RFC 7636 §4.1: 43 characters from the
        ``unreserved`` alphabet.
    """
    return secrets.token_urlsafe(CODE_VERIFIER_BYTES)


class DriveGrantError(RuntimeError):
    """The web flow could not be built or completed.

    Deliberately carries the underlying detail for the **server log** and never
    for a caller: an OAuth failure names the client id, the redirect URI and
    Google's own error code, all of which describe this deployment's wiring.
    Every adapter above translates it to one constant refusal.
    """


def _flow_class() -> Any:
    """Return ``google_auth_oauthlib.flow.Flow``, or say it is not installed.

    Split from :func:`build_flow` so that function holds one ``try`` rather
    than two: the import failure and the client-description failure are
    different conditions with different remedies — install a package, or fix a
    file — and folding them together would blur that in the server log.

    Returns:
        The flow class, typed ``Any`` because the Google libraries ship no type
        information and ``pyproject.toml`` ignores them for mypy.

    Raises:
        GoogleApiUnavailableError: When the optional Google libraries are not
            installed on this host.
    """
    try:
        from google_auth_oauthlib.flow import Flow
    except ImportError as exc:  # pragma: no cover - the extra is installed in CI
        msg = (
            "google-auth-oauthlib is required to authorise Google Drive. "
            "Install it with `pip install google-auth-oauthlib`."
        )
        raise GoogleApiUnavailableError(msg) from exc
    return Flow


def build_flow(
    *,
    credentials_file: str,
    scopes: Sequence[str],
    redirect_uri: str,
    code_verifier: str,
) -> Any:
    """Return a configured ``google_auth_oauthlib`` web ``Flow``.

    The single construction site, so a test substitutes one seam rather than
    reaching into two functions, and production has no second path.

    Args:
        credentials_file: Path to the **web** client secrets JSON. An
            installed-app file parses but cannot complete a redirect-based
            exchange, which is ADR-0012's one deployment requirement.
        scopes: The scope list to request. Validated by the caller against
            :data:`creek.config._READONLY_SCOPES` *before* it reaches here.
        redirect_uri: The caller-owned URI Google redirects the user's browser
            back to. Never a URI on this server; see ADR-0012 §1.
        code_verifier: The PKCE verifier this grant is bound to, from
            :func:`new_code_verifier`. Required rather than defaulted, and
            paired with ``autogenerate_code_verifier=False``, so no flow can
            silently mint its own: the URL leg publishes the challenge and the
            exchange leg presents the verifier, and they are different flow
            objects in different requests.

    Returns:
        The flow object, typed ``Any`` because the Google libraries ship no
        type information and ``pyproject.toml`` ignores them for mypy.

    Raises:
        GoogleApiUnavailableError: When the optional Google libraries are not
            installed on this host.
        DriveGrantError: When the client secrets file cannot be read or is not
            a usable OAuth client description.
    """
    flow_class = _flow_class()
    try:
        return flow_class.from_client_secrets_file(
            credentials_file,
            scopes=list(scopes),
            redirect_uri=redirect_uri,
            code_verifier=code_verifier,
            autogenerate_code_verifier=False,
        )
    except (OSError, ValueError, KeyError) as exc:
        msg = f"could not read the Google client secrets file: {exc}"
        raise DriveGrantError(msg) from exc


def authorization_url(flow: Any, *, state: str) -> str:
    """Return the URL the caller sends its user to, carrying *state*.

    Args:
        flow: A flow from :func:`build_flow`.
        state: The single-use value binding the eventual code to an
            authorization this server issued.

    Returns:
        The absolute Google authorization URL.

    Raises:
        DriveGrantError: When the flow cannot render a URL — a client
            description missing its ``auth_uri``, most plausibly.
    """
    try:
        url, _echoed_state = flow.authorization_url(
            state=state,
            access_type=_ACCESS_TYPE,
            prompt=_PROMPT,
            include_granted_scopes=_INCLUDE_GRANTED_SCOPES,
        )
    except (AttributeError, KeyError, TypeError, ValueError) as exc:
        msg = f"could not build the Google authorization URL: {exc}"
        raise DriveGrantError(msg) from exc
    return str(url)


def exchange_code(flow: Any, *, code: str) -> str:
    """Trade *code* for a credential and return it serialised.

    The one leg that carries the client secret, and the one that reaches
    Google's token endpoint. The returned text is exactly what
    ``Credentials.to_json()`` produces, so the token file this writes is
    byte-shaped like the one ``creek gdrive --download`` writes and
    :func:`creek.ingest.gdrive.inspect_token` reads either without knowing
    which minted it.

    Args:
        flow: A flow from :func:`build_flow`, configured with the *same*
            ``redirect_uri`` the authorization was issued under. Google
            rejects the exchange otherwise, which is a property this design
            relies on rather than works around.
        code: The authorization code the caller relayed.

    Returns:
        The serialised credential.

    Raises:
        DriveGrantError: When Google refused the exchange, the code was stale,
            or the flow yielded no credential. The reason travels no further
            than the server log.
    """
    try:
        flow.fetch_token(code=code)
        serialised = flow.credentials.to_json()
    except Exception as exc:  # the OAuth and HTTP stacks below raise broadly
        msg = f"the Google authorization code could not be exchanged: {exc}"
        raise DriveGrantError(msg) from exc
    if not serialised:
        msg = "the Google authorization exchange yielded no credential"
        raise DriveGrantError(msg)
    return str(serialised)
